#!/usr/bin/env python3
"""agent_views.py - generated views over missions + design-context ledger.

Stdlib only. Subcommands: digest | brief | index | queue | resume <mission>.

Generated files (never hand-edited):
  docs/agent-system/context/DIGEST.md        (<=150 lines)
  docs/agent-system/context/THINKER-BRIEF.md (<=250 lines)
  docs/agent-system/context/INDEX.md         (full insight list, one line each)
  docs/agent-system/missions/INDEX.md        (mission registry)
"""

import os
import re
import subprocess
import sys

import agent_lint as lint

REPO = lint.REPO
AGENT_SYS = lint.AGENT_SYS
MISSIONS = lint.MISSIONS
CONTEXT = lint.CONTEXT
INSIGHTS = os.path.join(CONTEXT, "insights")
INBOX = os.path.join(CONTEXT, "inbox")

DIGEST_BUDGET = 150
BRIEF_BUDGET = 250


def all_insights():
    out = []
    if not os.path.isdir(INSIGHTS):
        return out
    for fn in sorted(os.listdir(INSIGHTS)):
        if not fn.endswith(".md"):
            continue
        p = os.path.join(INSIGHTS, fn)
        text = lint.read_text(p)
        fm = lint.parse_front_matter(text)
        mtime = os.path.getmtime(p)
        out.append({"file": fn, "path": p, "text": text, "fm": fm,
                    "mtime": mtime})
    out.sort(key=lambda d: d["mtime"])
    return out


def claim_of(text):
    m = re.search(r"^Claim\s*$\n(.*?)(?=^#|\Z)", text, re.M | re.S)
    if m:
        para = m.group(1).strip().split("\n")[0].strip()
        return para[:180]
    for line in text.splitlines():
        s = line.strip()
        if s and not s.startswith(("#", ">", "`", "```", "---")):
            return s[:180]
    return "(no claim)"


def next_action_of(state_text):
    body = lint.section_body(state_text, "NEXT_ACTION")
    return body.split("\n")[0][:200] if body else "(none recorded)"


def active_missions():
    rows = []
    for name, mdir in lint.mission_dirs():
        text, fm = lint.read_state(mdir)
        if text is None:
            continue
        rows.append({"id": name, "fm": fm, "text": text})
    return rows


def cmd_digest(_args):
    missions = active_missions()
    insights = all_insights()
    lines = []
    lines.append("# DIGEST.md — active missions, decisions, questions (generated)")
    lines.append("")
    lines.append("> **Classification: DERIVED — CURRENT (generated by agent_views.py; never hand-edit)**")
    lines.append("")
    lines.append("## Active missions")
    lines.append("")
    seen_active = False
    for m in missions:
        st = str(m["fm"].get("status", "")).strip()
        if st in ("ACTIVE", "BLOCKED"):
            seen_active = True
            lines.append("- **%s** [%s] branch `%s` — NEXT: %s" % (
                m["id"], st, m["fm"].get("branch", "?"),
                next_action_of(m["text"])))
    if not seen_active:
        lines.append("- None. (no ACTIVE or BLOCKED missions)")
    lines.append("")
    lines.append("## Latest ADOPTED decisions")
    lines.append("")
    adopted = [i for i in insights
               if str(i["fm"].get("status", "")).upper() == "ADOPTED"]
    if adopted:
        for i in adopted[-10:]:
            lines.append("- %s: %s" % (i["file"], claim_of(i["text"])))
    else:
        lines.append("- None yet.")
    lines.append("")
    lines.append("## Open questions by recipient")
    lines.append("")
    qs = [i for i in insights
          if str(i["fm"].get("kind", "")).upper() == "QUESTION"
          and str(i["fm"].get("status", "")).upper() == "PROPOSED"]
    if qs:
        by_to = {}
        for i in qs:
            by_to.setdefault(str(i["fm"].get("to", "?")), []).append(i)
        for to in sorted(by_to):
            lines.append("### to: %s" % to)
            for i in by_to[to]:
                lines.append("- %s: %s" % (i["file"], claim_of(i["text"])))
    else:
        lines.append("- None.")
    lines.append("")
    lines.append("## 15 most recent insights")
    lines.append("")
    for i in insights[-15:]:
        lines.append("- [%s](insights/%s) %s/%s — %s" % (
            i["file"], i["file"], i["fm"].get("kind", "?"),
            i["fm"].get("status", "?"), claim_of(i["text"])))
    lines.append("")
    if len(lines) > DIGEST_BUDGET:
        lines = lines[:DIGEST_BUDGET]
    out = os.path.join(CONTEXT, "DIGEST.md")
    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print("wrote %s (%d lines)" % (os.path.relpath(out, REPO), len(lines)))
    return 0


def cmd_brief(_args):
    rc = cmd_digest([])
    if rc != 0:
        return rc
    with open(os.path.join(CONTEXT, "DIGEST.md"), "r",
              encoding="utf-8") as f:
        digest = f.read().splitlines()
    lines = []
    lines.append("# THINKER-BRIEF.md — what the coding agent needs from you (generated)")
    lines.append("")
    lines.append("> **Classification: DERIVED — CURRENT (generated by agent_views.py; never hand-edit)**")
    lines.append("")
    lines.append("## Digest (mirrored)")
    lines.append("")
    lines.extend(digest[3:])
    lines.append("")
    lines.append("## What the agent needs from you")
    lines.append("")
    insights = all_insights()
    asked = [i for i in insights
             if str(i["fm"].get("kind", "")).upper() == "QUESTION"
             and str(i["fm"].get("to", "")) == "thinker"
             and str(i["fm"].get("status", "")).upper() == "PROPOSED"]
    if asked:
        for i in asked:
            lines.append("- %s (working assumption + reversal cost inside; "
                         "answer with recommendation, confidence, and what "
                         "would change your mind)" % i["file"])
    else:
        lines.append("- Nothing outstanding. Review latest ADOPTED decisions "
                     "for critique.")
    lines.append("")
    lines.append("## Deposit format reminder")
    lines.append("")
    lines.append("End every session with a CONTEXT DEPOSIT block in the exact "
                 "v1 format from context/THINKER-PROTOCOL.md.")
    lines.append("")
    if len(lines) > BRIEF_BUDGET:
        lines = lines[:BRIEF_BUDGET]
    out = os.path.join(CONTEXT, "THINKER-BRIEF.md")
    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print("wrote %s (%d lines)" % (os.path.relpath(out, REPO), len(lines)))
    return 0


def cmd_index(_args):
    insights = all_insights()
    lines = []
    lines.append("# INDEX.md — every insight, one line each (generated)")
    lines.append("")
    lines.append("> **Classification: DERIVED — CURRENT (generated by agent_views.py; never hand-edit)**")
    lines.append("")
    for i in insights:
        fm = i["fm"]
        lines.append("- [%s](insights/%s) %s | %s | %s | %s" % (
            fm.get("id", i["file"]), i["file"], fm.get("date", "?"),
            fm.get("kind", "?"), fm.get("status", "?"),
            fm.get("author", "?")))
    out = os.path.join(CONTEXT, "INDEX.md")
    with open(out, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    print("wrote %s (%d insights)" % (os.path.relpath(out, REPO),
                                      len(insights)))
    lines2 = []
    lines2.append("# INDEX.md — mission registry (generated)")
    lines2.append("")
    lines2.append("> **Classification: DERIVED — CURRENT (generated by agent_views.py; never hand-edit)**")
    lines2.append("")
    lines2.append("| mission | status | branch | updated | next action |")
    lines2.append("|---|---|---|---|---|")
    for m in active_missions():
        lines2.append("| %s | %s | %s | %s | %s |" % (
            m["id"], m["fm"].get("status", "?"),
            m["fm"].get("branch", "?"), m["fm"].get("updated", "?"),
            next_action_of(m["text"])[:80]))
    out2 = os.path.join(MISSIONS, "INDEX.md")
    with open(out2, "w", encoding="utf-8") as f:
        f.write("\n".join(lines2) + "\n")
    print("wrote %s" % os.path.relpath(out2, REPO))
    return 0


def cmd_queue(_args):
    files = []
    if os.path.isdir(INBOX):
        files = sorted(f for f in os.listdir(INBOX)
                       if os.path.isfile(os.path.join(INBOX, f))
                       and not f.startswith("."))
    print("inbox: %d file(s) pending in docs/agent-system/context/inbox/" %
          len(files))
    for f in files:
        print("- " + f)
    return 0


def wip_refs(mission):
    code, out, _ = lint.git("for-each-ref",
                            "refs/wip/%s/" % mission,
                            "--format=%(refname) %(creatordate:iso8601)")
    refs = []
    if code == 0 and out.strip():
        for line in out.strip().splitlines():
            parts = line.split(" ", 1)
            refs.append(parts[0])
    return sorted(refs)


def cmd_resume(args):
    if not args:
        print("usage: agent_views.py resume <mission>")
        return 2
    mission = args[0]
    mdir = os.path.join(MISSIONS, mission)
    if not os.path.isdir(mdir):
        print("REFUSED: unknown mission '%s'" % mission)
        return 1
    text, fm = lint.read_state(mdir)
    if text is None:
        print("REFUSED: mission %s has no STATE.md" % mission)
        return 1
    branch = lint.current_branch()
    code, head, _ = lint.git("rev-parse", "HEAD")
    head = head.strip() if code == 0 else "?"
    claimed_branch = str(fm.get("branch", "")).strip()
    last_insp = str(fm.get("last_commit_inspected", "")).strip()
    print("mission: %s (status %s)" % (mission, fm.get("status", "?")))
    print("charter branch: %s | actual branch: %s" % (claimed_branch, branch))
    if claimed_branch != branch:
        print("FLAG: branch mismatch — STATE claims '%s' but git is on '%s'"
              % (claimed_branch, branch))
    print("last_commit_inspected: %s | HEAD: %s" % (last_insp, head))
    if last_insp and head != "?" and not head.startswith(last_insp) \
            and last_insp not in head:
        code2, out2, _ = lint.git("merge-base", "--is-ancestor", last_insp,
                                  "HEAD")
        if code2 != 0:
            print("FLAG: stale tip — last_commit_inspected %s is not an "
                  "ancestor of HEAD (%s)" % (last_insp, (out2 or "").strip()))
        else:
            print("note: HEAD is ahead of last_commit_inspected "
                  "(re-inspect, then update STATE)")
    refs = wip_refs(mission)
    print("latest wip ref: %s" % (refs[-1] if refs else "(none)"))
    print("POSITION: %s" % lint.section_body(text, "POSITION").split("\n")[0])
    print("NEXT_ACTION: %s" % next_action_of(text))
    print("DECISIONS_IN_FORCE:")
    for line in lint.section_body(text, "DECISIONS_IN_FORCE").splitlines():
        if line.strip():
            print("  " + line.strip())
    print("OPEN_QUESTIONS:")
    for line in lint.section_body(text, "OPEN_QUESTIONS").splitlines():
        if line.strip():
            print("  " + line.strip())
    return 0


def main(argv):
    if not argv or argv[0] in ("-h", "--help"):
        print("usage: agent_views.py digest|brief|index|queue|resume <mission>")
        return 2
    cmd = argv[0]
    if cmd == "digest":
        return cmd_digest(argv[1:])
    if cmd == "brief":
        return cmd_brief(argv[1:])
    if cmd == "index":
        return cmd_index(argv[1:])
    if cmd == "queue":
        return cmd_queue(argv[1:])
    if cmd == "resume":
        return cmd_resume(argv[1:])
    print("unknown subcommand '%s'" % cmd)
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
