/**
 * VIVIM Intelligence Substrate — NLCL Index (K0-L0)
 * @module intel/nlcl/index
 */
export * from './catalog.js'
export * from './command-registry.js'
export * from './types.js'
export { InMemoryConfirmationStore, NullConfirmationStore, type ConfirmationStore, type ConfirmationStoreCreateInput, type PendingConfirmation } from './confirmation-store.js'
export { DialogueSessionStore, InMemoryDialogueSessionStore, type DialogueSession } from './dialogue-session-store.js'
export * from './entity-resolution.js'
export * from './context-binder.js'
export * from './fuzzy-resolver.js'
export * from './fuzzy-matcher.js'
export * from './help-resolver.js'
export * from './nl-parser.js'
export * from './nlcl-engine.js'
export * from './nlcl-otel.js'
export * from './prerouter.js'
export * from './parameter-extraction.js'
export * from './pattern-match.js'
export * from './intent-resolver.js'
export * from './intent-router.js'
export * from './layered-resolver.js'
export * from './llm-slave-resolver.js'
export * from './semantic-resolver.js'
export * from './text-normalizer.js'
export * from './tfidf.js'
export * from './tfidf-embedding-provider.js'
export * from './response-interpreter.js'
export * from './workflow-synthesis-resolver.js'
export * from './executors/app-executor.js'
export * from './executors/browser-executor.js'
export * from './executors/capability-executor.js'
export * from './executors/conversation-executor.js'
export * from './executors/email-executor.js'
export * from './executors/file-executor.js'
export * from './executors/generic-browser-executor.js'
export * from './executors/index.js'
export * from './executors/provider-llm-executor.js'
export * from './executors/system-executor.js'
export * from './executors/workflow-executor.js'
